- name: Configurar Cluster Kubernetes com K3s
  hosts: servidores_web
  become: yes

  tasks:
    - name: Atualizar os pacotes do sistema
      apt:
        update_cache: yes
        upgrade: dist

    - name: Baixar e instalar o K3s (Kubernetes)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Garantir que o servico K3s esta rodando
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Dar permissao no arquivo de configuracao do cluster para o usuario ubuntu
      file:
        path: /etc/rancher/k3s/k3s.yaml
        mode: "0644"
